[project]
name = "rag-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docling>=2.73.1",
    "fastembed",
    "langchain>=1.2.10",
    "pandas>=2.3.3",
]
